export const GENRES = [
    "Indie",
    "Casual",
    "Action",
    "Adventure",
    "Simulation",
    "Strategy",
    "RPG",
    "Exploration",
    "Puzzle",
    "Arcade",
    "Horror",
    "Early Access",
    "Shooter",
    "Platformer",,
    "Free to Play",
    "Survival",
    "Roguelike",
    "Open World",
] as const;